### ISSUE TITLE
Change password option isn't working

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4447]

**Comment by anchapin** [comment]
This should be working on dev2 now. Can you try changing a password again?

**Comment by RDmitchell** [comment]
Instance: dev2
SHA:

When I click the Forgot Password on the login page, and then enter my email address, in this case rdmitchell+408@lbl.gov, I get the following email to reset my password
You're receiving this email because you requested a password reset for your user account at SEED / Dev 2.

Please go to the following page and choose a new password:

https://afc71fade5a1841b3b848ed958601864-1042822150.us-east-1.elb.amazonaws.com/accounts/password/reset/confirm/NTYx/bzi9ko-5efa03181a69bd81d176d77baaf5e017/

Your username, in case you’ve forgotten: [rdmitchell+408@lbl.gov](mailto:rdmitchell%2B408@lbl.gov)

Thanks for using our site!

The SEED / Dev 2 team

However, when I click the link, I get this message. 
![image](https://github.com/SEED-platform/seed/assets/6314950/dca4240f-e226-4aed-9824-834ee375f3d8)

**Comment by kflemin** [comment]
@anchapin did this issue get resolved?

**Comment by axelstudios** [comment]
This is still an issue on _all_ of our deployments - attempting to reset your password does not send an email (to junk or otherwise)

**Comment by perryr16** [comment]
I received emails from both dev1 and dev2, however the provided link url is incorrect. It is currently going to an amazon aws domain instead of the seed instance.

ex: 
the url provided in the email was https://a641c143e406f466a95fdd38695ab895-312368394.us-east-1.elb.amazonaws.com/accounts/password/reset/confirm/NTcx/cc5gxn-4cc7d5fceca9c98b51d0ac30be735675/

however the feature works if you replace "https://a641c143e406f466a95fdd38695ab895-312368394.us-east-1.elb.amazonaws.com" with "https://dev2.seed-platform.org/"

**Comment by kflemin** [comment]
@perryr16, could we use the site.domain to create the URL instead so we can make sure it goes to the right place? 

you should be able to get it from the "Site" model object, site.domain.

**Comment by perryr16** [comment]
@kflemin, yeah when testing locally the site.domain is incorrect. It can be changed pretty easily on an instance by instance basis. [The steps are listed here](https://github.com/SEED-platform/seed/blob/develop/docs/source/faq.rst#id4) but it would need to be done by someone with access to those instances. Another option would be to create a `SITE_DOMAIN` env variable on each instance and run a migration that uses that env var to set the site domain.
